"""Artifact model — project artifacts generated by agents.

Phase 6 — Final Migration & Handover
Artifacts are tied to specific tasks/executions with immutable IDs.
"""

from typing import Optional
from uuid import uuid4
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db import Base
from pydantic import BaseModel


class Artifact(Base):
    """Artifact model for project artifacts generated by agents."""
    __tablename__ = 'artifacts'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    content_type = Column(String(100), nullable=True)  # e.g., 'markdown', 'diagram', 'code'
    storage_path = Column(String(500), nullable=False)  # S3 path or local path
    task_id = Column(UUID(as_uuid=True), nullable=True)  # Optional: tie to task
    execution_id = Column(UUID(as_uuid=True), nullable=True)  # Optional: tie to execution
    version = Column(String(50), default='1.0', nullable=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc), nullable=False)
    meta_info = Column(JSON, default=dict, nullable=True)  # Tags, agent_id, etc.

    # Relationships
    task = relationship("Task", foreign_keys=[task_id])
    execution = relationship("Execution", foreign_keys=[execution_id])

    def __repr__(self):
        return f'<Artifact {self.name}>'


class ArtifactCreate(BaseModel):
    """Schema for creating an artifact."""
    name: str
    description: Optional[str] = None
    content_type: Optional[str] = None
    storage_path: str
    task_id: Optional[str] = None
    execution_id: Optional[str] = None
    version: str = '1.0'


class ArtifactResponse(BaseModel):
    """Schema for artifact responses."""
    id: str
    name: str
    description: Optional[str] = None
    content_type: Optional[str] = None
    storage_path: str
    task_id: Optional[str] = None
    execution_id: Optional[str] = None
    version: str
    created_at: datetime
    updated_at: datetime
    meta_info: dict