"""Artifact management API routes for viewing, inspecting, and managing project artifacts."""

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_

from app.db import get_db_session
from app.models import Artifact
from app.schemas.artifact import ArtifactResponse, ArtifactCreate, ArtifactUpdate
from app.auth import get_current_user

router = APIRouter(prefix="/artifacts", tags=["artifact", "management"])


def to_uuid(val) -> Optional[uuid.UUID]:
    if val is None or isinstance(val, uuid.UUID):
        return val
    try:
        return uuid.UUID(str(val))
    except (ValueError, AttributeError):
        return None


@router.get("/project/{project_id}", summary="List artifacts for project")
async def list_project_artifacts(
    project_id: str,
    artifact_type: Optional[str] = None,
    db_session: AsyncSession = Depends(get_db_session),
    current_user = Depends(get_current_user),
):
    """List all artifacts tied to a project, with optional filtering by type."""
    p_uuid = to_uuid(project_id)
    if not p_uuid:
        return []

    conditions = [Artifact.project_id == p_uuid]
    if artifact_type:
        conditions.append(Artifact.type == artifact_type)

    result = await db_session.execute(
        select(Artifact).where(and_(*conditions)).order_by(Artifact.created_at.desc())
    )
    artifacts = result.scalars().all()
    return [art.to_dict() for art in artifacts]


@router.get("/execution/{execution_id}", summary="List artifacts for execution")
async def list_execution_artifacts(
    execution_id: str,
    db_session: AsyncSession = Depends(get_db_session),
    current_user = Depends(get_current_user),
):
    """List artifacts generated by or linked to a specific execution."""
    result = await db_session.execute(
        select(Artifact).order_by(Artifact.created_at.desc())
    )
    artifacts = result.scalars().all()
    return [art.to_dict() for art in artifacts]


@router.get("/task/{task_id}", summary="List artifacts for task")
async def list_task_artifacts(
    task_id: str,
    db_session: AsyncSession = Depends(get_db_session),
    current_user = Depends(get_current_user),
):
    """List artifacts associated with a specific task."""
    t_uuid = to_uuid(task_id)
    if not t_uuid:
        return []

    result = await db_session.execute(
        select(Artifact).where(Artifact.task_id == t_uuid).order_by(Artifact.created_at.desc())
    )
    artifacts = result.scalars().all()
    return [art.to_dict() for art in artifacts]


@router.get("/{artifact_id}", summary="Get artifact details")
async def get_artifact(
    artifact_id: str,
    db_session: AsyncSession = Depends(get_db_session),
    current_user = Depends(get_current_user),
):
    """Get full details of a single artifact."""
    a_uuid = to_uuid(artifact_id)
    if not a_uuid:
        raise HTTPException(status_code=404, detail="Artifact not found")

    result = await db_session.execute(select(Artifact).where(Artifact.id == a_uuid))
    artifact = result.scalar_one_or_none()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")

    return artifact.to_dict()


@router.get("/{artifact_id}/content", summary="Read content of artifact file")
async def get_artifact_content(
    artifact_id: str,
    db_session: AsyncSession = Depends(get_db_session),
    current_user = Depends(get_current_user),
):
    """Read the text content of a generated artifact."""
    a_uuid = to_uuid(artifact_id)
    if not a_uuid:
        raise HTTPException(status_code=404, detail="Artifact not found")

    result = await db_session.execute(select(Artifact).where(Artifact.id == a_uuid))
    artifact = result.scalar_one_or_none()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")

    content = ""
    file_path = Path(artifact.path)
    if file_path.exists() and file_path.is_file():
        try:
            content = file_path.read_text(encoding="utf-8")
        except Exception as e:
            content = f"Could not decode content: {e}"
    else:
        content = artifact.description or "No file content available on disk."

    return {
        "id": str(artifact.id),
        "name": artifact.name,
        "type": artifact.type,
        "path": str(artifact.path),
        "content": content
    }